- name: include vault
  include_vars:
    file: vault.yml

- name: include vars
  include_vars:
    file: ../vars/main.yml

- name: create location for config file
  file:
    path: /opt/docker-compose/prowlarr/
    owner: prowlarr
    group: prowlarr
    state: directory

- name: create location for config file
  file:
    path: /opt/docker-compose/prowlarr/config/
    owner: prowlarr
    group: prowlarr
    state: directory

- name: deploy environment file
  template:
    src: ../templates/config.xml
    dest: /opt/docker-compose/prowlarr/config/config.xml
    owner: prowlarr
    group: prowlarr
