---
version: "2.1"
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=2080
      - PGID=2080
      - TZ=America/New_York
    volumes:
      - /mnt/nzbget/config:/config
      - /mnt/nzbget/downloads:/data/downloads #optional
    ports:
      - 6789:6789
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1

networks:
  default:
    name: overlay_arr_network
    external: true
