services:
  archivebox:
    container_name: archivebox
    image: archivebox/archivebox:dev
    command: server --quick-init 0.0.0.0:8000
#    ports:
#      - 8000:8000
    volumes:
      - ./data:/data
      - /mnt/archivebox/data/archive:/data/archive
      - /mnt/archivebox/logs:/data/logs
    environment:
      - ALLOWED_HOSTS=*
      - TZ=America/New_York
      - PUID=5020
      - PGID=5020
      - ADMIN_USERNAME={{ vault_archivebox_admin_username }}
      - ADMIN_PASSWORD={{ vault_archivebox_admin_password }}
    networks:
      - archivebox
      - nginx-bridge

networks:
  archivebox:
  nginx-bridge:
    external: true
