version: '3.9'
services:
  archivebox:
    container_name: archivebox
    image: archivebox/archivebox:latest
    command: server --quick-init 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - /mnt/archivebox/data:/data
    environment:
      - ALLOWED_HOSTS=*
      - PGUID=5020
      - PGID=5020
      - TZ=America/New_York    