services:
  libreSpeed:
    container_name: librespeed
    restart: unless-stopped
    #ports:
    #  - '8086:80'
    environment:
      - MODE=standalone
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - PASSWORD=testPassword
      - PUID=5005
      - PGID=5005
      - TZ=America/New_York
    image: adolfintel/speedtest
    networks:
      - nginx-bridge    
    
networks:
  nginx-bridge:
    name: nginx-bridge
    external: true    