services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    mem_limit: 4g
    security_opt:
      - no-new-privileges:true
#    ports:
#      - 5000:5000
    environment:
      LT_LOAD_ONLY: en,fr,de,es,ru,zh
      PUID : 5045
      PGID : 5045
      TZ : America/New_York
    networks:
      - nginx-bridge    
    
networks:
  nginx-bridge:
    name: nginx-bridge
    external: true