version: '3.3'
services:
  libreSpeed:
    container_name: librespeed
    restart: always
    ports:
      - '8086:80'
    environment:
      - MODE=standalone
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - PASSWORD=testPassword
      - PUID=5005
      - PGID=5005
      - TZ=America/New_York  
    image: adolfintel/speedtest
