services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-ngx-broker
    restart: unless-stopped
    volumes:
      - ./data/redisdata:/data
    networks:
      - paperless-ngx

  db:
    image: docker.io/library/postgres:15
    container_name: paperless-ngx-db
    restart: unless-stopped
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - paperless-ngx

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx-frontend
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8123:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/:/usr/src/paperless/data
      - /mnt/paperless_ngx/media/:/usr/src/paperless/media
      - /mnt/paperless_ngx/export/:/usr/src/paperless/export
      - /mnt/paperless_ngx/consume/:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
    networks:
      - paperless-ngx

networks:
  paperless-ngx: