services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: mastrick-syncthing
    environment:
      - PUID=5050
      - PGID=5050
      - TZ=America/New_York
    volumes:
      - /mnt/syncthing/:/var/syncthing
    ports:
#     - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
#    network_mode: host
    networks:
      - syncthing
      - nginx-bridge

networks:
  syncthing:
  nginx-bridge:
    external: true
