  glances:
    container_name: glances
    restart: always
    ports:
      - '61208-61209:61208-61209'
    environment:
      - GLANCES_OPT=-w
      - PUID=3005
      - PGID=3005
      - TZ=America/New_York      
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    pid: host
    image: docker.io/nicolargo/glances
