version: "3.8"
services:
  gamevault-backend:
    image: phalcode/gamevault-backend:latest
    container_name: gamevault-server
    restart: unless-stopped
    environment:
      DB_HOST: gamevault-db
      DB_USERNAME: {{ vault_gamevault_db_username }}
      DB_PASSWORD: {{ vault_gamevault_db_password }}
      # The following line grants Admin Role to the account with this username upon registration.
      SERVER_ADMIN_USERNAME: {{ vault_gamevault_server_admin_username }}
      # Uncomment and insert your RAWG API Key here if you have one (http://rawg.io/login?forward=developer)
      RAWG_API_KEY: {{ vault_gamevault_rawg_api_key }}
      PUID: 6060
      PGID: 6060
      TZ: America/New_York      
    volumes:
      # Mount the folder where your games are
      - /mnt/gamevault/files:/files
      # Mount the folder where GameVault should store its images
      - /mnt/gamevault/images:/images
    ports:
      - 8612:8080
      
  db:
    image: postgres:15
    container_name: gamevault-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: {{ vault_gamevault_db_username }}
      POSTGRES_PASSWORD: {{ vault_gamevault_db_password }}
      POSTGRES_DB: gamevault
    volumes:
      - ./data:/var/lib/postgresql/data