- name: create location for environment config file
  file:
    path: "{{ item }}"
    owner: nzbget
    group: nzbget
    state: directory
  with_items:
   - '/mnt/nzbget/downloads'
   - '/mnt/nzbget/config'

- name: deploy config script
  copy:
    src: ../files/nzbget.conf
    dest: /mnt/nzbget/config/nzbget.conf
    owner: 2080
    group: 2080
    remote_src: no
