version: '3.3'
services:
  libreSpeed:
    restart: always
    ports:
      - '8086:80'
    environment:
      - MODE=standalone
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - PASSWORD=testPassword
    image: adolfintel/speedtest
