users:
 - app: 'glances'
   username:  'glances'
   groupname: 'glances'
   uid: 3005
   gid: 3005
 - app: 'librespeed'
   username: 'librespeed'
   groupname: 'librespeed'
   uid: 5005
   gid: 5005
 - app: 'pyload-ng'
   username: 'pyload-ng'
   groupname: 'pyload-ng'
   uid: 5010
   gid: 5010
   mounts:
     - mount: '/mnt/pyload_ng'
       servicename: 'mnt-pyload_ng.mount'
       device: '//10.10.125.202/pyload_ng'
       fstype: 'cifs'
       username: 'pyload_ng'
   directories:
     - directory: /mnt/pyload_ng
 - app: 'archivebox'
   username: 'archivebox'
   groupname: 'archivebox'
   uid: 5020
   gid: 5020
   mounts:
     - mount: '/mnt/archivebox'
       servicename: 'mnt-archivebox.mount'
       device: '//10.10.125.201/archivebox'
       fstype: 'cifs'
       username: 'ArchiveBox'
   directories:
     - directory: /mnt/archivebox
 - app: 'manyfold'
   username: 'manyfold'
   groupname: 'manyfold'
   uid: 5075
   gid: 5075
   mounts:
     - mount: '/mnt/manyfold'
       servicename: 'mnt-manyfold.mount'
       device: '//10.10.125.201/manyfold'
       fstype: 'cifs'
       username: 'manyfold'
 - app: 'ghostfolio'
   username: 'ghostfolio'
   groupname: 'ghostfolio'
   uid: 5040
   gid: 5040
   mounts:
     - mount: '/mnt/ghostfolio'
       servicename: 'mnt-ghostfolio.mount'
       device: '//10.10.125.202/ghostfolio'
       fstype: 'cifs'
       username: 'ghostfolio'
   prereq:
     - template_name: ".env"
       destination: "/opt/docker-compose/ghostfolio/.env"
 - app: 'syncthing'
   username: 'syncthing'
   groupname: 'syncthing'
   uid: 5050
   gid: 5050
   mounts:
     - mount: '/mnt/syncthing'
       servicename: 'mnt-syncthing.mount'
       device: '//10.10.125.201/syncthing'
       fstype: 'cifs'
       username: 'syncthing'
 - app: 'paperless_ngx'
   username: 'paperless_ngx'
   groupname: 'paperless_ngx'
   uid: 5060
   gid: 5060
   mounts:
     - mount: '/mnt/paperless_ngx'
       servicename: 'mnt-paperless_ngx.mount'
       device: '//10.10.125.201/paperless_ngx'
       fstype: 'cifs'
       username: 'paperless_ngx'
   directories:
     - /opt/docker-compose/paperless_ngx
     - /mnt/paperless_ngx/data
     - /mnt/paperless_ngx/media
     - /mnt/paperless_ngx/export
     - /mnt/paperless_ngx/consume
   prereq:
     - template_name: "docker-compose.env"
       destination: "/opt/docker-compose/paperless_ngx/docker-compose.env"
 - app: 'viewtube'
   username: 'viewtube'
   groupname: 'viewtube'
   uid: 5015
   gid: 5015
   mounts:
     - mount: '/mnt/viewtube'
       servicename: 'mnt-viewtube.mount'
       device: '//10.10.125.202/viewtube'
       fstype: 'cifs'
       username: 'viewtube'
   directories:
       - "/opt/docker-compose/viewtube/data"
 - app: 'piped'
   username: 'piped'
   groupname: 'piped'
   uid: 5017
   gid: 5017
   directories:
     - "/opt/docker-compose/piped"
     - "/opt/docker-compose/piped/config/"
   prereq:
     - template_name: "config.properties"
       destination: "/opt/docker-compose/piped/config/config.properties"
     - template_name: "nginx.conf"
       destination: "/opt/docker-compose/piped/config/nginx.conf"
     - template_name: "pipedapi.conf"
       destination: "/opt/docker-compose/piped/config/pipedapi.conf"
     - template_name: "pipedfrontend.conf"
       destination: "/opt/docker-compose/piped/config/pipedfrontend.conf"
     - template_name: "pipedproxy.conf"
       destination: "/opt/docker-compose/piped/config/pipedproxy.conf"
     - template_name: "ytproxy.conf"
       destination: "/opt/docker-compose/piped/config/ytproxy.conf"
 - app: 'watchtower'
   username: 'watchtower'
   groupname: 'watchtower'
   uid: 9090
   gid: 9090
 - app: 'nginx'
   servicename: nginx
   username: 'nginx'
   groupname: 'nginx'
   uid: 9000
   gid: 9000
 - app: 'it-tools'
   username: 'it-tools'
   groupname: 'it-tools'
   uid: 5025
   gid: 5025
 - app: 'stirling-pdf'
   username: 'stirling-pdf'
   groupname: 'stirling-pdf'
   uid: 5030
   gid: 5030
   mounts:
     - mount: '/mnt/stirling_pdf'
       servicename: 'mnt-stirling_pdf.mount'
       device: '//10.10.125.201/stirling_pdf'
       fstype: 'cifs'
       username: 'stirling_pdf'
 - app: 'flatnotes'
   username: 'flatnotes'
   groupname: 'flatnotes'
   uid: 5035
   gid: 5035
   mounts:
     - mount: '/mnt/flatnotes'
       servicename: 'mnt-flatnotes.mount'
       device: '//10.10.125.201/flatnotes'
       fstype: 'cifs'
       username: 'flatnotes'
 - app: 'libretranslate'
   username: 'libretranslate'
   groupname: 'libretranslate'
   uid: 5045
   gid: 5045
 - app: 'muer'
   username: 'muer'
   groupname: 'muer'
   uid: 6020
   gid: 6020
 - app: 'uptime-kuma'
   username: 'uptime_kuma'
   groupname: 'uptime_kuma'
   uid: 3010
   gid: 3010
 - app: 'romm'
   username: 'romm'
   groupname: 'romm'
   uid: 6090
   gid: 6090
   directories:
     - '/mnt/romm'
     - '/mnt/romm/emulators'
   mounts:
     - mount: '/mnt/romm/emulators'
       servicename: 'mnt-romm-emulators.mount'
       device: '//10.10.125.201/emulators'
       fstype: 'cifs'
       username: 'romm'
 - app: 'your_spotify'
   username: 'your_spotify'
   groupname: 'your_spotify'
   uid: 6050
   gid: 6050
 - app: 'gamevault'
   username: 'gamevault'
   groupname: 'gamevault'
   uid: 6060
   gid: 6060
   directories:
     - '/mnt/gamevault'
     - '/mnt/gamevault/files'
     - '/mnt/gamevault/images'
   mounts:
     - mount: '/mnt/gamevault/files'
       servicename: 'mnt-gamevault-files.mount'
       device: '//10.10.125.201/games/data'
       fstype: 'cifs'
       username: 'gamevault'
     - mount: '/mnt/gamevault/images'
       servicename: 'mnt-gamevault-images.mount'
       device: '//10.10.125.201/games/gamevault/images'
       fstype: 'cifs'
       username: 'gamevault'
 - app: 'openspeedtest'
   username: 'openspeedtest'
   groupname: 'openspeedtest'
   uid: 5055
   gid: 5055
 - app: 'metube'
   username: 'metube'
   groupname: 'metube'
   uid: 6070
   gid: 6070
   mounts:
     - mount: '/mnt/metube'
       servicename: 'mnt-metube.mount'
       device: '//10.10.125.202/metube'
       fstype: 'cifs'
       username: 'metube'
   directories:
       - "/opt/docker-compose/metube/downloads"
 - app: 'dozzle'
   username: 'dozzle'
   groupname: 'dozzle'
   uid: 3020
   gid: 3020
 - app: 'tubearchivist'
   username: 'tubearchivist'
   groupname: 'tubearchivist'
   uid: 6080
   gid: 6080
   mounts:
     - mount: '/mnt/tubearchivist'
       servicename: 'mnt-tubearchivist.mount'
       device: '//10.10.125.202/Videos/web/youtube'
       fstype: 'cifs'
       username: 'tubearchivist'
     - mount: '/mnt/nas02/home'
       servicename: 'mnt-nas02-home.mount'
       device: '10.10.125.202:/home/'
       fstype: 'nfs'
 - app: 'forgejo'
   username: 'forgejo'
   groupname: 'forgejo'
   uid: 3030
   gid: 3030
   mounts:
    # - mount: '/mnt/forgejo'
    #   servicename: 'mnt-forgejo.mount'
    #   device: '//10.10.125.202/forgejo'
    #   fstype: 'cifs'
    #   username: 'forgejo'
     - mount: '/mnt/homelab_forgejo'
       servicename: 'mnt-nas02-homelab_forgejo.mount'
       device: '10.10.125.202:/homelab_forgejo/'
       fstype: 'nfs'
 - app: 'plex'
   username: 'plex'
   groupname: 'plex'
   uid: 9001
   gid: 9001
   mounts:
     -  mount: '/mnt/nas02/Videos/movies/anime'
        servicename: 'mnt-nas02-Videos-movies-anime.mount'
        device: '//10.10.125.202/Videos/movies/anime'
        fstype: 'cifs'
        username: 'plex'
     -  mount: '/mnt/nas02/Videos/movies/hd'
        servicename: 'mnt-nas02-Videos-movies-hd.mount'
        device: '//10.10.125.202/Videos/movies/hd'
        fstype: 'cifs'
        username: 'plex'
     -  mount: '/mnt/nas02/Videos/movies/uhd'
        servicename: 'mnt-nas02-Videos-movies-uhd.mount'
        device: '//10.10.125.202/Videos/movies/uhd'
        fstype: 'cifs'
        username: 'plex'
     -  mount: '/mnt/nas02/Videos/tv/anime'
        servicename: 'mnt-nas02-Videos-tv-anime.mount'
        device: '//10.10.125.202/Videos/tv/anime'
        fstype: 'cifs'
        username: 'plex'
     -  mount: '/mnt/nas02/Videos/tv/hd'
        servicename: 'mnt-nas02-Videos-tv-hd.mount'
        device: '//10.10.125.202/Videos/tv/hd'
        fstype: 'cifs'
        username: 'plex'
     -  mount: '/mnt/nas02/Videos/tv/uhd'
        servicename: 'mnt-nas02-Videos-tv-uhd.mount'
        device: '//10.10.125.202/Videos/tv/uhd'
        fstype: 'cifs'
        username: 'plex'
 - app: 'bookstack'
   username: 'bookstack'
   groupname: 'bookstack'
   uid: 5065
   gid: 5065
