users:
 - app: 'glances'
   username:  'glances'
   groupname: 'glances'
   uid: 3005
   gid: 3005
 - app: 'libreSpeed'
   username: 'librespeed'
   groupname: 'librespeed'
   uid: 5005
   gid: 5005
 - app: 'pyload'
   username: 'pyload'
   groupname: 'pyload'
   uid: 5010
   gid: 5010
 - app: 'ArchiveBox'
   username: 'archivebox'
   groupname: 'archivebox'
   uid: 5020
   gid: 5020
 - app: 'Ghostfolio'
   username: 'ghostfolio'
   groupname: 'ghostfolio'
   uid: 5040
   gid: 5040
 - app: 'Syncthing'
   username: 'syncthing'
   groupname: 'syncthing'
   uid: 5050
   gid: 5050
 - app: 'Prowlarr'
   username: 'prowlarr'
   groupname: 'prowlarr'
   uid: 2010
   gid: 2010
 - app: 'NZBGet'
   username: 'nzbget'
   groupname: 'nzbget'
   uid: 2080
   gid: 2080
 - app: 'ViewTube'
   username: 'viewtube'
   groupname: 'viewtube'
   uid: 5015
   gid: 5015
 - app: 'Piped'
   username: 'piped'
   groupname: 'piped'
   uid: 5017
   gid: 5017
 - app: 'sonarr_hd'
   username: 'sonarr_hd'
   groupname: 'sonarr_hd'
   uid: 2060
   gid: 2060
 - app: 'sonarr_uhd'
   username: 'sonarr_uhd'
   groupname: 'sonarr_uhd'
   uid: 2061
   gid: 2061
 - app: 'sonarr_anime'
   username: 'sonarr_anime'
   groupname: 'sonarr_anime'
   uid: 2062
   gid: 2062
 - app: 'torrent_qbt'
   username: 'torrent_qbt'
   groupname: 'torrent_qbt'
   uid: 2070
   gid: 2070
 - app: 'gluetun'
   username: 'gluetun'
   groupname: 'gluetun'
   uid: 2000
   gid: 2000
 - app: 'radarr_hd'
   username: 'radarr_hd'
   groupname: 'radarr_hd'
   uid: 2050
   gid: 2050
 - app: 'radarr_uhd'
   username: 'radarr_uhd'
   groupname: 'radarr_uhd'
   uid: 2051
   gid: 2051
 - app: 'radarr_anime'
   username: 'radarr_anime'
   groupname: 'radarr_anime'
   uid: 2052
   gid: 2052
 - app: 'recyclarr'
   username: 'recyclarr'
   groupname: 'recyclarr'
   uid: 2020
   gid: 2020
 - app: 'watchtower'
   username: 'watchtower'
   groupname: 'watchtower'
   uid: 9090
   gid: 9090
 - app: 'invidious'
   username: 'invidious'
   groupname: 'invidious'
   uid: 6000
   gid: 6000
