- name: create passwordless su group
  group:
    name: passwordfreesu
    gid: 9999
    state: present

- name: add ansible to group
  user:
    name: ansible
    groups: passwordfreesu
    append: yes

- name: ansible power up
  lineinfile:
    path: /etc/pam.d/su
    state: present
    line: auth sufficient pam_succeed_if.so use_uid user ingroup passwordfreesu
