- name: create location for base
  file:
    path: /opt/docker-compose/nginx
    owner: nginx
    group: nginx
    state: directory  

- name: create location for certbot
  file:
    path: /opt/docker-compose/nginx/certbot
    owner: nginx
    group: nginx
    state: directory

- name: create location for config
  file:
    path: /opt/docker-compose/nginx/config
    owner: nginx
    group: nginx
    state: directory
    
- name: create location for nginx location
  file:
    path: "/opt/docker-compose/nginx/config/locations-{{ application_group }}"
    owner: nginx
    group: nginx
    state: directory
    
- name: copy nginx host config
  copy:
    src: "{{ item }}"
    dest: /opt/docker-compose/nginx/config
    owner: nginx
    group: nginx
  with_fileglob: ../files/core/nginx.*.conf
  register: nginx_host
  
- name: copy nginx server config
  copy:
    src: "{{ item }}"
    dest: "/opt/docker-compose/nginx/config/{{ item | basename | regex_replace('nginx.server.(.*)$', '\\1') }}" 
    owner: nginx
    group: nginx
  with_fileglob: ../files/{{ application_group }}/nginx.server.*.conf
  register: nginx_server
  
- name: copy nginx server config
  copy:
    src: "{{ item }}"
    dest: "/opt/docker-compose/nginx/config/locations-{{ application_group }}/{{ item | basename | regex_replace('nginx.location.(.*)$', '\\1') }}" 
    owner: nginx
    group: nginx
  with_fileglob: ../files/{{ application_group }}/nginx.location.*.conf
  register: nginx_location
  
- name: create nginx network
  docker_network:
    name: nginx
  
- name: create nginx bridge network
  docker_network:
    name: nginx-bridge
    driver_options:
      com.docker.network.bridge.name: nginx-bridge  

  #start container
- name: Restart container for nginx
  community.docker.docker_compose_v2:
    project_src: "/opt/docker-compose/nginx/"
    state: restarted
  register:
    restarted
  when: nginx_host.changed or nginx_server.changed or nginx_location.changed
  
- name: Start container for nginx
  community.docker.docker_compose_v2:
    project_src: "/opt/docker-compose/nginx/"
    state: present
  #when: (nginx_host.changed or nginx_server.changed or nginx_location.changed) and (restarted is not change)