- name: create location for base
  file:
    path: /opt/docker-compose/nginx
    owner: nginx
    group: nginx
    state: directory  

- name: create location for certbot
  file:
    path: /opt/docker-compose/nginx/certbot
    owner: nginx
    group: nginx
    state: directory

- name: create location for config
  file:
    path: /opt/docker-compose/nginx/config
    owner: nginx
    group: nginx
    state: directory
    
- name: create location for nginx location
  file:
    path: "/opt/docker-compose/nginx/config/locations-{{ application_group }}"
    owner: nginx
    group: nginx
    state: directory
    
- name: copy nginx host config
  copy:
    src: "{{ item }}"
    dest: /opt/docker-compose/nginx/config
    owner: nginx
    group: nginx
  with_fileglob: ../files/core/nginx.*.conf
  
- name: copy nginx server config
  copy:
    src: "{{ item }}"
    dest: "/opt/docker-compose/nginx/config/{{ item | basename | regex_replace('nginx.server.(.*)$', '\\1') }}" 
    owner: nginx
    group: nginx
  with_fileglob: ../files/{{ application_group }}/nginx.server.*.conf
  
- name: copy nginx server config
  copy:
    src: "{{ item }}"
    dest: "/opt/docker-compose/nginx/config/locations-{{ application_group }}/{{ item | basename | regex_replace('nginx.location.(.*)$', '\\1') }}" 
    owner: nginx
    group: nginx
  with_fileglob: ../files/{{ application_group }}/nginx.location.*.conf
  
- name: create nginx network
  docker_network:
    name: nginx
  
- name: create nginx bridge network
  docker_network:
    name: nginx-bridge
    driver_options:
      com.docker.network.bridge.name: nginx-bridge  
    