- name: include users for "{{ application.name }}"
  include_vars:
    file: users.yml

- name: include map
  include_vars:
    file: maps.yml

- name: lower application name for "{{ application.name }}"
  set_fact:
    app_name_lower: "{{ application.name | lower }}"

- name: get application config for "{{ application.name }}"
  set_fact:
    app_config: "{{ users | selectattr('app', 'equalto', app_name_lower) | first }}"

- name: get application id for "{{ application.name }}"
  set_fact:
    app_service_name : "{{ app_config.servicename | default(app_name_lower) }}"
    
- name: get mount names for "{{ application.name }}"
  set_fact:
    app_mount_names : "{{ app_config.mounts | join(' ') }}"
  when: app_config.mounts is defined
  
- name: get mount names for "{{ application.name }}"
  set_fact:
    app_mount_names : ""
  when: app_config.mounts is not defined
    
- name: vars for "{{ application.name }}"
  set_fact:
    pre_path:  "roles/{{ app_name_lower }}/tasks/pre.yml"
    post_path: "roles/{{ app_name_lower }}/tasks/post.yml"
    service_name: "docker-compose.{{ app_service_name }}.service"
    compose_path: "/opt/docker-compose/{{ app_service_name }}/docker-compose.yml"

- name: vars2 for "{{ application.name }}"
  set_fact:
    service_path: "/etc/systemd/system/{{ service_name }}"

- name: create workspace for "{{ application.name }}"
  include_tasks:
    file: tasks/user_and_group.yml
  vars:
    app: "{{ app_name_lower }}"

- name: Check for prereqs for "{{ application.name }}"
  become: no
  local_action: stat path="{{ pre_path }}"
  register: prereq

- name: Do prereqs for "{{ application.name }}"
  include_tasks:
    file: "{{ pre_path }}"
  when: prereq.stat.exists

- name: add user to docker group for "{{ application.name }}"
  user:
    name: "{{ app_config.username }}"
    groups: docker
    append: yes

- name: Make sure destination dir exists for "{{ application.name }}"
  file:
    path: "{{ compose_path | dirname }}"
    state: directory
    owner: "{{ app_config.username }}"
    group: "{{ app_config.groupname }}"

- name: Copy compose file for "{{ application.name }}"
  template:
    src: "roles/{{ app_name_lower }}/templates/docker-compose.yml"
    dest: "{{ compose_path }}"
    owner: "{{ app_config.username }}"
    group: "{{ app_config.groupname }}"
  register: compose

- name: Check for postreqs for "{{ application.name }}"
  become: no
  local_action: stat path="{{ post_path }}"
  register: post_deploy

- name: Do post deploy for "{{ application.name }}"
  include_tasks:
    file: "{{ post_path }}"
  when: post_deploy.stat.exists
  register:
    post_deploy_action

- name: Deploy service for "{{ application.name }}"
  template:
    src: ../templates/docker-compose.service
    dest: "{{ service_path }}"
  register:
    service

- name: Restart service for "{{ application.name }}"
  service:
    name: "{{ service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: compose.changed or post_deploy_action.changed or service.changed
