---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_hd
    environment:
      - PUID=2060
      - PGID=2060
      - TZ=America/New_York
    volumes:
      - ./config/:/config
      - /mnt/sonarr_hd/tv:/data/tv #optional
      - /mnt/sonarr_hd/downloads:/data/downloads #optional
      - /mnt/sonarr_hd/torrents:/data/torrents/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1

networks:
  default:
    name: overlay_arr_network
    external: true
