- hosts: arr
  become: yes
  become_method: sudo
  roles:
    - ansible_client
    - docker
  tasks:
    - set_fact:
        applications:
          - name : Recyclarr

    - name: setup application
      include_tasks:
        file: tasks/setup_application.yml
      vars:
        application: "{{ item }}"
        application_group: "arr"
      with_items: "{{ applications }}"

    - name: setup nginx
      include_tasks:
        file: tasks/nginx.yml
      vars:
        application_group: "arr"

    - name: setup vpn reset
      include_tasks:
        file: roles/arr/tasks/cron-vpn-reset.yml
