- hosts: all
  become: yes
  become_method: sudo
  roles:
    - ansible_client
    - docker
  tasks:
    - set_fact:
        applications:
          - name : glances
          - name : dozzle          
          
    - name: setup application
      include_tasks:
        file: tasks/setup_application.yml
      vars:
        application: "{{ application_name }}"
        application_group: "core"
      with_items: "{{ applications }}"
      loop_control:
        loop_var: application_name          
