- hosts: homelab01
  become: yes
  become_method: sudo
  roles:
    - ansible_client
    - docker
  tasks:
    - set_fact:
        applications:
<<<<<<< HEAD
          - name : ArchiveBox
          - name : libreSpeed
          - name : Ghostfolio
          - name : Syncthing
          - name : Paperless_NGX
          - name : IT-Tools
          - name : Stirling-PDF
          - name : flatnotes
          - name : LibreTranslate
          - name : Uptime-Kuma
          - name : OpenSpeedTest
=======
#          - name : ArchiveBox
#          - name : libreSpeed
#          - name : Ghostfolio
#          - name : Syncthing
#          - name : Paperless_NGX
#          - name : IT-Tools
#          - name : Stirling-PDF
#          - name : flatnotes
#          - name : LibreTranslate
#          - name : Uptime-Kuma
#          - name : OpenSpeedTest
>>>>>>> 8629f04 (Added forgejo)
          - name : Forgejo

    - name: setup application
      include_tasks:
        file: tasks/setup_application.yml
      vars:
        application: "{{ application_name }}"
        application_group: "homelab"
      with_items: "{{ applications }}"
      loop_control:
        loop_var: application_name

    - name: setup application
      include_tasks:
        file: tasks/nginx.yml
      vars:
        application_group: "homelab"
