- hosts: homelab01
  become: yes
  become_method: sudo
#  roles:
#    - docker
  tasks:
    - name: docker compose
      include_role:
        name: docker-compose
      vars:
        application: glances
