- hosts: stream
  become: yes
  become_method: sudo
  roles:
    - ansible_client
    - docker
  tasks:
    - set_fact:
        applications:
          - name : Invidious
          - name : ViewTube
          - name : Piped
          - name : Muer
          - name : RomM
          - name : Your_Spotify
          - name : MeTube
          - name : TubeArchivist

    - name: setup application
      include_tasks:
        file: tasks/setup_application.yml
      vars:
        application: "{{ item }}"
        application_group: "stream"
      with_items: "{{ applications }}"

    - name: setup application
      include_tasks:
        file: tasks/setup_application.yml
      vars:
        application:
          name: "nginx"
        application_group: "core"

    - name: setup application
      include_tasks:
        file: tasks/nginx.yml
      vars:
        application_group: "stream"
