- hosts: stream
  become: yes
  become_method: sudo
  roles:
    - ansible_client
    - docker
  tasks:
    - set_fact:
        applications:
          - name : Invidious
          - name : ViewTube          
          - name : Piped
          - name : Nginx_Stream          

    - name: setup application
      include_tasks:
        file: tasks/setup_application.yml
      vars:
        application: "{{ item }}"
      with_items: "{{ applications }}"
