- name: "Include secrets"
  include_vars:
    file: vault.yml

- name: "Get variables"
  include_vars:
    file: ../vars/main.yml

- name: get cifs util for path
  apt:
    pkg:
      - cifs-utils
    state: present

- name: "Set variables"
  set_fact:
    user:
      uid : 2060
      gid : 2060

- set_fact:
    fstab:
      user: "sonarr_hd"
      group: "sonarr_hd"
      mount: "/mnt/sonarr_hd/downloads"
      device: "//10.10.125.202/nzb/downloads"
      fstype: "cifs"
      options: "username={{ samba_creds.username }},password={{ samba_creds.password }},iocharset=utf8,uid={{ user.uid }},gid={{ user.gid }},file_mode=0755,dir_mode=0755,vers=3.1.1"

- include_tasks:
    file: tasks/fstab.yml
  vars:
    entry: "{{ fstab }}"

- set_fact:
    fstab:
      user: "sonarr_hd"
      group: "sonarr_hd"
      mount: "/mnt/sonarr_hd/tv"
      device: "//10.10.125.202/Videos/tv/hd"
      fstype: "cifs"
      options: "username={{ samba_creds.username }},password={{ samba_creds.password }},iocharset=utf8,uid={{ user.uid }},gid={{ user.gid }},file_mode=0755,dir_mode=0755,vers=3.1.1"

- include_tasks:
    file: tasks/fstab.yml
  vars:
    entry: "{{ fstab }}"

- set_fact:
    fstab:
      user: "sonarr_hd"
      group: "sonarr_hd"
      mount: "/mnt/sonarr_hd/torrents"
      device: "//10.10.125.202/torrent/downloads"
      fstype: "cifs"
      options: "username={{ samba_creds.username }},password={{ samba_creds.password }},iocharset=utf8,uid={{ user.uid }},gid={{ user.gid }},file_mode=0755,dir_mode=0755,vers=3.1.1"

- include_tasks:
    file: tasks/fstab.yml
  vars:
    entry: "{{ fstab }}"

