---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=2010
      - PGID=2010
      - TZ=America/New_York
    volumes:
      - /opt/docker-compose/prowlarr/config/:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1

networks:
  default:
    external:
      name: overlay_arr_network
