services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: "container:gluetun"
    container_name: prowlarr
    environment:
      - PUID=2010
      - PGID=2010
      - TZ=America/New_York
    volumes:
      - /opt/docker-compose/prowlarr/config/:/config
    restart: unless-stopped
