services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr_hd
    environment:
      - PUID=2060
      - PGID=2060
      - TZ=America/New_York
    volumes:
      - ./config/:/config
      - /mnt/sonarr_hd/tv:/data/tv #optional
      - /mnt/sonarr_hd/downloads:/data/downloads #optional
      - /mnt/sonarr_hd/torrents:/data/torrents/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - overlay_arr_network
      - nginx-bridge

networks:
  overlay_arr_network:
    external: true
  nginx-bridge:
    external: true
  
